zonal_benchmarking: False
reuse_same_mount: False
iterations: 3

bench_env:
  delete_after_use: True
  zone: us-central1-b
  project: gcs-fuse-test
  gce_env:
    vm_name: cpranjal-a4x-test
    machine_type:
    image_family:
    image_project:
    disk_size:
    startup_script: resources/starter_script.sh
  gcs_bucket:
    bucket_name: # Leaving placement empty will create a regional bucket in the region of the zone.

    placement:
    storage_class:
    enable_hns: True

fio_jobfile_template_path: resources/jobfile.fio

job_details:
  file_path: resources/fio_job_cases.csv

version_details:
  go_version: 1.22.0
  fio_version: 3.36
  gcsfuse_version_or_commit: v3.2.0
