cache-dir: /mnt/lssd
file-cache:
  cache-file-for-range-read: true
  enable-parallel-downloads: true
  max-size-mb: -1
metadata-cache:
  stat-cache-max-size-mb: -1
  ttl-secs: -1
  type-cache-max-size-mb: -1
implicit-dirs: true
